export const reviews = [
  {
    id: 1,
    name: "أحمد",
    gender: "male",
    stars: 5,
    verified: true,
    date: "قبل يومين",
    comment: "والله انقذني اكثر من مره",
  },
  {
    id: 2,
    name: "ساره",
    gender: "female",
    stars: 5,
    verified: true,
    date: "قبل 5 أيام",
    comment: "اخذت الوردي مره حلو",
  },
  {
    id: 3,
    name: "عبدالله",
    gender: "male",
    stars: 5,
    verified: true,
    date: "قبل أسبوع",
    comment: "وصل بسرعه وشغال زي الفل",
  },
  {
    id: 4,
    name: "ريم",
    gender: "female",
    stars: 5,
    verified: true,
    date: "قبل أسبوع",
    comment: "صغير وخفيف مره",
  },
  {
    id: 5,
    name: "فيصل",
    gender: "male",
    stars: 5,
    verified: true,
    date: "قبل أسبوعين",
    comment: "الخامه ممتازه وشكله فخم",
  },
  {
    id: 6,
    name: "نوره",
    gender: "female",
    stars: 5,
    verified: true,
    date: "قبل أسبوعين",
    comment: "شحن الايفون عندي بدون مشاكل",
  },
  {
    id: 7,
    name: "محمد",
    gender: "male",
    stars: 5,
    verified: true,
    date: "قبل 3 أسابيع",
    comment: "اخذت الاسود وطلع مره جميل",
  },
  {
    id: 8,
    name: "جود",
    gender: "female",
    stars: 5,
    verified: true,
    date: "قبل شهر",
    comment: "الوردي احلى من الصور",
  },
  {
    id: 9,
    name: "ماجد",
    gender: "male",
    stars: 5,
    verified: true,
    date: "قبل شهر",
    comment: "عملي مره وقت الطواري",
  },
  {
    id: 10,
    name: "شهد",
    gender: "female",
    stars: 5,
    verified: true,
    date: "قبل شهر",
    comment: "وصلني بسرعه والتغليف مرتب",
  },
  {
    id: 11,
    name: "خالد",
    gender: "male",
    stars: 5,
    verified: true,
    date: "قبل شهرين",
    comment: "صار معي بكل مكان",
  },
  {
    id: 12,
    name: "لولوه",
    gender: "female",
    stars: 5,
    verified: true,
    date: "قبل شهرين",
    comment: "يستاهل السعر صراحه",
  },
  {
    id: 13,
    name: "سلطان",
    gender: "male",
    stars: 5,
    verified: true,
    date: "قبل شهرين",
    comment: "فادني اكثر من مره",
  },
  {
    id: 14,
    name: "رغد",
    gender: "female",
    stars: 5,
    verified: true,
    date: "قبل شهرين",
    comment: "خفيف وما ياخذ مكان",
  },
  {
    id: 15,
    name: "يوسف",
    gender: "male",
    stars: 5,
    verified: true,
    date: "قبل 3 أشهر",
    comment: "ركبته مع المفاتيح وخلاص",
  },
  {
    id: 16,
    name: "مها",
    gender: "female",
    stars: 5,
    verified: true,
    date: "قبل 3 أشهر",
    comment: "استخدمه بشكل يومي",
  },
  {
    id: 17,
    name: "تركي",
    gender: "male",
    stars: 5,
    verified: true,
    date: "قبل 3 أشهر",
    comment: "افضل من اني اشيل باور بانك كبير",
  },
  {
    id: 18,
    name: "هناء",
    gender: "female",
    stars: 5,
    verified: true,
    date: "قبل 3 أشهر",
    comment: "مره عملي وانصح فيه",
  },
  {
    id: 19,
    name: "سعود",
    gender: "male",
    stars: 5,
    verified: true,
    date: "قبل 4 أشهر",
    comment: "جودته فوق المتوقع",
  },
  {
    id: 20,
    name: "غاده",
    gender: "female",
    stars: 5,
    verified: true,
    date: "قبل 4 أشهر",
    comment: "اشتريته لي واختي وعجبنا",
  },

  {
    id: 21,
    name: "علي",
    gender: "male",
    stars: 5,
    verified: true,
    date: "قبل 4 أشهر",
    comment: "صراحه فادني كثير وقت طلعت البطاريه فجأه",
  },
  {
    id: 22,
    name: "دلال",
    gender: "female",
    stars: 5,
    verified: true,
    date: "قبل 4 أشهر",
    comment: "اخذت الوردي مره حلو واحلى من الصور",
  },
  {
    id: 23,
    name: "عبدالرحمن",
    gender: "male",
    stars: 5,
    verified: true,
    date: "قبل 5 أشهر",
    comment: "صغير بشكل مو طبيعي وهذا اكثر شي عجبني",
  },
  {
    id: 24,
    name: "أريج",
    gender: "female",
    stars: 5,
    verified: true,
    date: "قبل 5 أشهر",
    comment: "احطه مع المفاتيح ولا احس فيه",
  },
  {
    id: 25,
    name: "نايف",
    gender: "male",
    stars: 5,
    verified: true,
    date: "قبل 5 أشهر",
    comment: "وصل بسرعه وشغال زي الوصف",
  },
  {
    id: 26,
    name: "أمل",
    gender: "female",
    stars: 5,
    verified: true,
    date: "قبل 5 أشهر",
    comment: "مره عملي خصوصا اذا طلعت كثير",
  },
  {
    id: 27,
    name: "زياد",
    gender: "male",
    stars: 5,
    verified: true,
    date: "قبل 6 أشهر",
    comment: "اشتريته وما ندمت ابدا",
  },
  {
    id: 28,
    name: "لمياء",
    gender: "female",
    stars: 5,
    verified: true,
    date: "قبل 6 أشهر",
    comment: "خفيف وحلو وما ياخذ مكان",
  },
  {
    id: 29,
    name: "تركي",
    gender: "male",
    stars: 5,
    verified: true,
    date: "قبل 6 أشهر",
    comment: "يستاهل كل ريال اندفع فيه",
  },
  {
    id: 30,
    name: "منيره",
    gender: "female",
    stars: 5,
    verified: true,
    date: "قبل 6 أشهر",
    comment: "شكله مره مرتب والخامه كويسه",
  },
  {
    id: 31,
    name: "بدر",
    gender: "male",
    stars: 5,
    verified: true,
    date: "قبل 7 أشهر",
    comment: "كل اصحابي سألوني من وين شريته",
  },
  {
    id: 32,
    name: "ريم",
    gender: "female",
    stars: 5,
    verified: true,
    date: "قبل 7 أشهر",
    comment: "انقذني اكثر من مره والله",
  },
  {
    id: 33,
    name: "فهد",
    gender: "male",
    stars: 5,
    verified: true,
    date: "قبل 7 أشهر",
    comment: "كويس مره للي يطلع كثير",
  },
  {
    id: 34,
    name: "هبه",
    gender: "female",
    stars: 5,
    verified: true,
    date: "قبل 7 أشهر",
    comment: "اخذت واحد لي ووحده لاختي",
  },
  {
    id: 35,
    name: "عبدالعزيز",
    gender: "male",
    stars: 5,
    verified: true,
    date: "قبل 8 أشهر",
    comment: "اللون الاسود مره فخم",
  },
  {
    id: 36,
    name: "جمانه",
    gender: "female",
    stars: 5,
    verified: true,
    date: "قبل 8 أشهر",
    comment: "صغير ولطيف مره",
  },
  {
    id: 37,
    name: "راشد",
    gender: "male",
    stars: 5,
    verified: true,
    date: "قبل 8 أشهر",
    comment: "كنت متردد بس طلع ممتاز",
  },
  {
    id: 38,
    name: "سندس",
    gender: "female",
    stars: 5,
    verified: true,
    date: "قبل 8 أشهر",
    comment: "وصل بسرعه والتغليف مرتب",
  },
  {
    id: 39,
    name: "يزيد",
    gender: "male",
    stars: 5,
    verified: true,
    date: "قبل 9 أشهر",
    comment: "الحين صار معي بكل مكان",
  },
  {
    id: 40,
    name: "هند",
    gender: "female",
    stars: 5,
    verified: true,
    date: "قبل 9 أشهر",
    comment: "والله يستاهل الشرا",
  },
];
