export const reviews = [
  {
    id: 1,
    name: "أحمد محمد",
    gender: "male",
    stars: 5,
    verified: true,
    date: "قبل يومين",
    comment: "المنتج ممتاز جداً، حجمه صغير والشحن سريع وأنصح فيه.",
  },
  {
    id: 2,
    name: "سارة",
    gender: "female",
    stars: 5,
    verified: true,
    date: "قبل أسبوع",
    comment: "الجودة ممتازة واللون الأبيض جميل جداً.",
  },
  {
    id: 3,
    name: "عبدالله",
    gender: "male",
    stars: 5,
    verified: true,
    date: "قبل أسبوع",
    comment: "وصل بسرعة والتغليف ممتاز.",
  },
  {
    id: 4,
    name: "ريم",
    gender: "female",
    stars: 4,
    verified: true,
    date: "قبل أسبوعين",
    comment: "منتج عملي جداً وسهل الحمل.",
  },
  {
    id: 5,
    name: "فيصل",
    gender: "male",
    stars: 5,
    verified: true,
    date: "قبل أسبوعين",
    comment: "أفضل باور بانك بالحجم هذا.",
  },
  {
    id: 6,
    name: "نورة",
    gender: "female",
    stars: 5,
    verified: true,
    date: "قبل شهر",
    comment: "أنصح فيه لأي شخص يستخدم الجوال كثير.",
  },
  {
    id: 7,
    name: "محمد",
    gender: "male",
    stars: 5,
    verified: true,
    date: "قبل شهر",
    comment: "الشحن سريع جداً والجودة عالية.",
  },
  {
    id: 8,
    name: "جود",
    gender: "female",
    stars: 5,
    verified: true,
    date: "قبل شهر",
    comment: "اشتريته هدية وأعجب الجميع.",
  },
  {
    id: 9,
    name: "ماجد",
    gender: "male",
    stars: 5,
    verified: true,
    date: "قبل شهر",
    comment: "الحجم صغير لكن الأداء ممتاز.",
  },
  {
    id: 10,
    name: "شهد",
    gender: "female",
    stars: 5,
    verified: true,
    date: "قبل شهر",
    comment: "وصلني بنفس اللون المطلوب.",
  },
  {
    id: 11,
    name: "خالد",
    gender: "male",
    stars: 4,
    verified: true,
    date: "قبل شهرين",
    comment: "البطارية جيدة جداً.",
  },
  {
    id: 12,
    name: "لولوة",
    gender: "female",
    stars: 5,
    verified: true,
    date: "قبل شهرين",
    comment: "خامة ممتازة ويستحق السعر.",
  },
  {
    id: 13,
    name: "سلطان",
    gender: "male",
    stars: 5,
    verified: true,
    date: "قبل شهرين",
    comment: "أنصح فيه بقوة.",
  },
  {
    id: 14,
    name: "رغد",
    gender: "female",
    stars: 5,
    verified: true,
    date: "قبل شهرين",
    comment: "الشحن كان سريع جداً.",
  },
  {
    id: 15,
    name: "يوسف",
    gender: "male",
    stars: 5,
    verified: true,
    date: "قبل 3 أشهر",
    comment: "أستخدمه يومياً بدون أي مشاكل.",
  },
  {
    id: 16,
    name: "مها",
    gender: "female",
    stars: 5,
    verified: true,
    date: "قبل 3 أشهر",
    comment: "خفيف ويناسب الشنطة.",
  },
  {
    id: 17,
    name: "تركي",
    gender: "male",
    stars: 4,
    verified: true,
    date: "قبل 3 أشهر",
    comment: "أداء ممتاز وسعر مناسب.",
  },
  {
    id: 18,
    name: "هناء",
    gender: "female",
    stars: 5,
    verified: true,
    date: "قبل 3 أشهر",
    comment: "من أفضل المنتجات التي طلبتها.",
  },
  {
    id: 19,
    name: "سعود",
    gender: "male",
    stars: 5,
    verified: true,
    date: "قبل 4 أشهر",
    comment: "الجودة فاقت توقعاتي.",
  },
  {
    id: 20,
    name: "غادة",
    gender: "female",
    stars: 5,
    verified: true,
    date: "قبل 4 أشهر",
    comment: "منتج جميل ويستحق الشراء.",
  },
];
